<?php
// drop this into your theme for testing :)
use MVRK\Icenberg\Icenberg;

$ice = new Icenberg('tests', false);

$ice->wrap(
    [
        '<h3>TEXT</h3>',
        $ice->get_element('test_text, options', 'h1', ['blorbus', 'flomp']),
        '<h3>TEXTAREA</h3>',
        $ice->get_element('test_text_area, options'),
        '<h3>NUMBER</h3>',
        $ice->get_element('test_number'),
        '<h3>RANGE</h3>',
        $ice->get_element('test_range  '),
        '<h3>EMAIL</h3>',
        $ice->get_element('test_email'),
        '<h3>URL</h3>',
        $ice->get_element('test_url'),
        '<h3>PASSWORD</h3>',
        $ice->get_element('test_password'),
        '<h3>PALETTE</h3>',
        $ice->get_element('test_editor_palette'),
        '<h3>IMAGE</h3>',
        $ice->get_element('test_image'),
        '<h3>FILE ARRAY</h3>',
        $ice->get_element('test_file_array'),
        '<h3>FILE VIDEO ARRAY</h3>',
        $ice->get_element('test_file_video_array'),
        '<h3>FILE URL</h3>',
        $ice->get_element('test_file_url'),
        '<h3>VIDEO URL</h3>',
        $ice->get_element('test_file_video_url'),
        '<h3>WYSIWYG</h3>',
        $ice->get_element('test_wysiwyg'),
        '<h3>EMBED</h3>',
        $ice->get_element('test_embed'),
        '<h3>GALLERY</h3>',
        $ice->get_element('test_gallery'),
        '<h3>TABLE</h3>',
        $ice->get_element('test_table', 'h1', ['clormp']),
        '<h3>LINK ARRAY</h3>',
        $ice->get_element('test_link_array'),
        '<h3>LINK URL</h3>',
        $ice->get_element('test_link_url'),
        '<h3>POST OBJECT OBJECT</h3>',
        $ice->get_element('test_post_object_object'),
        '<h3>POST OBJECT ID</h3>',
        $ice->get_element('test_post_object_id'),
        '<h3>PAGE LINK MULTIPLE</h3>',
        $ice->get_element('test_page_link_multiple'),
        '<h3>PAGE LINK SINGULAR</h3>',
        $ice->get_element('test_page_link_singular'),
        '<h3>RELATIONSHIP</h3>',
        $ice->get_element('test_relationship'),
        '<h3>FORM</h3>',
        $ice->get_element('test_form'),
        '<h3>MAP</h3>',
        $ice->get_element('test_map'),
        '<h3>GROUP</h3>',
        $ice->get_element('test_group'),
        '<h3>REPEATER</h3>',
        $ice->get_element('test_repeater, options', 'h1', ['clormp']),

    ]
);
